@file:OptIn(ExperimentalUnsignedTypes::class)

package com.ivieleague.decompiler6502tokotlin.smb

/**
 * Stub functions and constants for decompiled SMB code.
 *
 * These are placeholders for functions and constants that weren't
 * automatically generated by the decompiler. They need to be properly
 * implemented for the game to work correctly.
 */

// ====================
// Missing Constants
// ====================

// Boot offset constants (low byte addresses)
const val ColdBootOffset = 0xFE  // <$07FE
const val WarmBootOffset = 0xD6  // <$07D6

// Music header offset - this references MusicHeaderData - 1
// TODO: Calculate actual value from MusicHeaderData address
const val MusicHeaderOffsetData = 0x0000

// Swim tile offset - references PlayerGraphicsTable + $9E
// TODO: Calculate actual value from PlayerGraphicsTable address
const val SwimTileRepOffset = 0x0000

// ====================
// Stub Functions
// ====================

// No-op functions (just return, do nothing)
fun noInitCode() {}
fun noRunCode() {}
fun noMoveCode() {}
fun endOfEnemyInitCode() {}
fun endFrenzy() {}

// TODO: Implement these properly

// Enemy initialization functions
fun initGoomba() { /* TODO */ }
fun initBloober() { /* TODO */ }
fun initBowser() { /* TODO */ }
fun initBulletBill() { /* TODO */ }
fun initCheepCheep() { /* TODO */ }
fun initDropPlatform() { /* TODO */ }
fun initEnemyFrenzy() { /* TODO */ }
fun initHammerBro() { /* TODO */ }
fun initHoriPlatform() { /* TODO */ }
fun initJumpGPTroopa() { /* TODO */ }
fun initLakitu() { /* TODO */ }
fun initLongFirebar() { /* TODO */ }
fun initRedKoopa() { /* TODO */ }
fun initRedPTroopa() { /* TODO */ }
fun initRetainerObj() { /* TODO */ }
fun initShortFirebar() { /* TODO */ }
fun initVertPlatform() { /* TODO */ }
fun initBalPlatform() { /* TODO */ }

// Enemy movement/run functions
fun runFirebarObj() { /* TODO */ }
fun runLargePlatform() { /* TODO */ }
fun runSmallPlatform() { /* TODO */ }
fun runBowser() { /* TODO */ }
fun runBowserFlame() { /* TODO */ }
fun runFireworks() { /* TODO */ }
fun runNormalEnemies() { /* TODO */ }
fun runStarFlagObj() { /* TODO */ }

// Enemy move functions
fun moveBloober() { /* TODO */ }
fun moveBulletBill() { /* TODO */ }
fun moveFlyGreenPTroopa() { /* TODO */ }
fun moveFlyingCheepCheep() { /* TODO */ }
fun moveLakitu() { /* TODO */ }
fun moveLargeLiftPlat() { /* TODO */ }
fun movePiranhaPlant() { /* TODO */ }
fun movePodoboo() { /* TODO */ }
fun moveSwimmingCheepCheep() { /* TODO */ }
fun procHammerBro() { /* TODO */ }
fun procMoveRedPTroopa() { /* TODO */ }

// Platform functions
fun balancePlatform() { /* TODO */ }
fun dropPlatform() { /* TODO */ }
fun largeLiftUp() { /* TODO */ }
fun largeLiftDown() { /* TODO */ }
fun rightPlatform() { /* TODO */ }
fun xMovingPlatform() { /* TODO */ }
fun yMovingPlatform() { /* TODO */ }

// Player state functions
// playerCtrlRoutine() is now properly decompiled in SMBDecompiled.kt
// playerEntrance is now properly implemented in SMBDecompiled.kt
fun playerChangeSize() { /* TODO */ }
fun playerFireFlower() { /* TODO */ }
fun playerInjuryBlink() { /* TODO */ }
fun playerDeath() { /* TODO */ }
fun playerLoseLife() { /* TODO */ }
fun playerVictoryWalk() { /* TODO */ }
fun playerEndLevel() { /* TODO */ }
fun playerEndWorld() { /* TODO */ }
// jumpSwimSub(), climbingSub(), fallingSub(), onGroundStateSub() are now properly decompiled in SMBDecompiled.kt
fun flagpoleSlide() { /* TODO */ }

// Game mode functions
fun gameMode(): Int = 0  // Returns game mode value
fun titleScreenMode() { /* TODO */ }
fun gameOverMode() { /* TODO */ }
fun victoryMode() { /* TODO */ }
fun setupVictoryMode() { /* TODO */ }
fun printVictoryMessages() { /* TODO */ }
// entranceGametimersetup() is now properly decompiled in SMBDecompiled.kt

// Block/tile functions
fun coinBlock() { /* TODO */ }
fun mushFlowerBlock() { /* TODO */ }
fun extraLifeMushBlock() { /* TODO */ }
fun starBlock() { /* TODO */ }
fun vineBlock() { /* TODO */ }
fun powerUpObjHandler() { /* TODO */ }
fun jumpspringHandler() { /* TODO */ }
fun vineObjectHandler() { /* TODO */ }
fun vineAutoclimb() { /* TODO */ }

// Area/level functions
fun areaParserCore() { /* TODO */ }
fun renderAreaGraphics() { /* TODO */ }
fun incrementColumnPos() { /* TODO */ }
fun warpZoneObject() { /* TODO */ }
fun bridgeCollapse() { /* TODO */ }

// Entry/exit functions
fun verticalPipeEntry() { /* TODO */ }
fun sideExitPipeEntry() { /* TODO */ }
fun pwrUpJmp() { /* TODO */ }

// Kotlin doesn't have a built-in `not` function - implement as bitwise NOT
fun not(value: Int): Int = value.inv() and 0xFF

// ====================
// Extension functions for MemoryByteArray arithmetic
// ====================

// When a MemoryByteArray is used without index, treat it as [0]
operator fun com.ivieleague.decompiler6502tokotlin.hand.MemoryByteArray.minus(other: Int): Int = this[0] - other
operator fun Int.minus(other: com.ivieleague.decompiler6502tokotlin.hand.MemoryByteArray): Int = this - other[0]
operator fun com.ivieleague.decompiler6502tokotlin.hand.MemoryByteArray.plus(other: Int): Int = this[0] + other
operator fun Int.plus(other: com.ivieleague.decompiler6502tokotlin.hand.MemoryByteArray): Int = this + other[0]
infix fun com.ivieleague.decompiler6502tokotlin.hand.MemoryByteArray.and(other: Int): Int = this[0] and other
infix fun Int.and(other: com.ivieleague.decompiler6502tokotlin.hand.MemoryByteArray): Int = this and other[0]
infix fun com.ivieleague.decompiler6502tokotlin.hand.MemoryByteArray.or(other: Int): Int = this[0] or other
infix fun Int.or(other: com.ivieleague.decompiler6502tokotlin.hand.MemoryByteArray): Int = this or other[0]
operator fun com.ivieleague.decompiler6502tokotlin.hand.MemoryByteArray.compareTo(other: Int): Int = this[0].compareTo(other)
fun com.ivieleague.decompiler6502tokotlin.hand.MemoryByteArray.toInt(): Int = this[0]

// Allow assigning to MemoryByteArray[0] via operator
// Note: This doesn't work in Kotlin - val cannot be reassigned even with extensions
// The proper fix requires codegen changes to use [0] index explicitly
