@file:OptIn(ExperimentalUnsignedTypes::class)

package com.ivieleague.decompiler6502tokotlin.smb

/**
 * Stub functions and constants for decompiled SMB code.
 *
 * These are placeholders for functions and constants that weren't
 * automatically generated by the decompiler. They need to be properly
 * implemented for the game to work correctly.
 */

// ====================
// Missing Constants
// ====================

// Boot offset constants (low byte addresses)
const val ColdBootOffset = 0xFE  // <$07FE
const val WarmBootOffset = 0xD6  // <$07D6

// Music header offset - this references MusicHeaderData - 1
// TODO: Calculate actual value from MusicHeaderData address
const val MusicHeaderOffsetData = 0x0000

// Swim tile offset - references PlayerGraphicsTable + $9E
// TODO: Calculate actual value from PlayerGraphicsTable address
const val SwimTileRepOffset = 0x0000

// ====================
// Helper Functions
// ====================

// Kotlin doesn't have a built-in `not` function - implement as bitwise NOT
fun not(value: Int): Int = value.inv() and 0xFF

// ====================
// Extension functions for MemoryByteArray arithmetic
// ====================

// When a MemoryByteArray is used without index, treat it as [0]
operator fun com.ivieleague.decompiler6502tokotlin.hand.MemoryByteArray.minus(other: Int): Int = this[0] - other
operator fun Int.minus(other: com.ivieleague.decompiler6502tokotlin.hand.MemoryByteArray): Int = this - other[0]
operator fun com.ivieleague.decompiler6502tokotlin.hand.MemoryByteArray.plus(other: Int): Int = this[0] + other
operator fun Int.plus(other: com.ivieleague.decompiler6502tokotlin.hand.MemoryByteArray): Int = this + other[0]
infix fun com.ivieleague.decompiler6502tokotlin.hand.MemoryByteArray.and(other: Int): Int = this[0] and other
infix fun Int.and(other: com.ivieleague.decompiler6502tokotlin.hand.MemoryByteArray): Int = this and other[0]
infix fun com.ivieleague.decompiler6502tokotlin.hand.MemoryByteArray.or(other: Int): Int = this[0] or other
infix fun Int.or(other: com.ivieleague.decompiler6502tokotlin.hand.MemoryByteArray): Int = this or other[0]
operator fun com.ivieleague.decompiler6502tokotlin.hand.MemoryByteArray.compareTo(other: Int): Int = this[0].compareTo(other)
fun com.ivieleague.decompiler6502tokotlin.hand.MemoryByteArray.toInt(): Int = this[0]
